version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.25-latest
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  whoami:
    image: traefik/whoami
    restart: always
    command: --verbose
