version: '3.7'

networks:
  authentik_default:
    name: local_default

services:
  traefik:
    image: docker.io/library/traefik:v2.9
    networks:
      - authentik_default
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  test-app-a:
    image: ghcr.io/stefanprodan/podinfo:6.2.2
    labels:
      traefik.enable: true
      traefik.http.routers.test-app-a.rule: Host(`localhost.dev.goauthentik.io`)
      traefik.http.routers.test-app-a.middlewares: authentik@docker
      traefik.http.routers.test-app-a_anon.rule: Host(`anon-test-app-a.localhost.dev.goauthentik.io`)
    networks:
      - authentik_default
  authentik-proxy:
    image: ghcr.io/goauthentik/proxy:latest
    env_file:
      - ../.env
    labels:
      traefik.enable: true
      traefik.port: 9000
      traefik.http.routers.authentik.rule: Host(`localhost.dev.goauthentik.io`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.middlewares.authentik.forwardauth.address: http://authentik-proxy:9000/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeadersRegex: ^.*$$
    restart: unless-stopped
    networks:
      - authentik_default
