---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 10.3.2
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 1h0m0s
  releaseName: traefik
  values:
    globalArguments:
      - "--global.checknewversion"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetescrd.allowCrossNamespace=true"
    ingressRoute:
      dashboard:
        enabled: false
    ingressClass:
      enabled: true
      isDefaultClass: true
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
        format: json
