---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 10.3.2
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 1h0m0s
  releaseName: traefik
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
